project_id = "ikgwsdviewtvaitlpijg"

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-ad-checkout]
verify_jwt = false
